= Mapping schema

== Overview

This is the documentation about the JSON schema file. The actual file is located in the ASAM OpenMATERIAL 3D link:https://github.com/asam-ev/OpenMATERIAL-3D/blob/main/schemas/mapping_schema.json[GitHub repository].

The following diagram shows the hierarchy of the fields defined in this schema. Fields marked with `\(R)` are required. A field can be optional while some of its children are required. In that case, the required children only have to be filled in if the optional parent field is present.

[plantuml]
----
legend
Mapping schema
|_ [[../07_geometry/mapping-schema.html#_metadata metadata]] (R)
  |_ [[../07_geometry/mapping-schema.html#_name name]] (R)
  |_ [[../07_geometry/mapping-schema.html#_description description]]
  |_ [[../07_geometry/mapping-schema.html#_uuid uuid]] (R)
  |_ [[../07_geometry/mapping-schema.html#_mappingversion mappingVersion]] (R)
  |_ [[../07_geometry/mapping-schema.html#_openmaterial3dversion openMaterial3dVersion]] (R)
  |_ [[../07_geometry/mapping-schema.html#_copyrights copyrights]] (R)
  |_ [[../07_geometry/mapping-schema.html#_license license]] (R)
  |_ [[../07_geometry/mapping-schema.html#_authors authors]] (R)
  |_ [[../07_geometry/mapping-schema.html#_creationdate creationDate]]
|_ [[../07_geometry/mapping-schema.html#_materialmapping materialMapping]] (R)
end legend
----

== metadata

The key meta information about the mapping table, including its identity, authorship, technical specifications, and legal details.


*Type:* `++object++` +
*Required:* Yes

=== name
The display name of the material mapping table.

*Type:* `++string++` +
*Required:* Yes


=== description
Short description of the mapping table in two to three sentences.

*Type:* `++string++` +
*Required:* No


=== uuid
Universally unique identifier for the mapping table in 8-4-4-4-12 format, see cite:[uui]. The uuid stays the same, even if version is updated.

*Type:* `++string++` +
*Pattern:* `++\b[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}\b$++` +
*Required:* Yes


=== mappingVersion
The version number of the mapping table, following semantic versioning (for example, '1.0.0').

*Type:* `++string++` +
*Pattern:* `++^\d+\.\d+\.\d+$++` +
*Required:* Yes


=== openMaterial3dVersion
The version of the ASAM OpenMATERIAL 3D specification used, adhering to semantic versioning (for example, '1.0.0').

*Type:* `++string++` +
*Pattern:* `++^\d+\.\d+\.\d+$++` +
*Required:* Yes


=== copyrights
Indicates copyright details, including the year and copyright holder (for example, '© 2024 ACME Inc.').

*Type:* `++array++` +
*Item count:* `++at least 1++` +
*Item type:* `++string++` +
*Required:* Yes


=== license
Describes the license for mapping table distribution. Use an SPDX identifier for open-source licenses (for example, 'MIT'), or provide a URL or filename for proprietary licenses.

*Type:* `++string++` +
*Required:* Yes


=== authors
Lists the author(s) of the mapping table as a name, email, or company.

*Type:* `++array++` +
*Item count:* `++at least 1++` +
*Item type:* `++string++` +
*Required:* Yes


=== creationDate
The date and time of mapping table creation, formatted as YYYYMMDDTHHMMSSZ according to ISO 8601 cite:[iso8601] (for example, '20240703T101728Z').

*Type:* `++string++` +
*Pattern:* `++^\d{8}T\d{6}Z$++` +
*Required:* No


== materialMapping

Array containing material mappings.


*Type:* `++array++` +
*Required:* Yes


*Column count:* `++exactly 3++`

Columns of the table:

[cols="1,2,2,6",options="header"]
|===
| Column | Type | Constraints | Description

| 1 | string |  | Material name or RGB code. The RGB code represents color values in an ASAM OpenMATERIAL 3D assignment texture. RGB codes are formatted as rgb:<R>;<G>;<B>. <R>, <G>, and <B> are integers in the range [0, 255].
| 2 | string | `++.*\.xomp$++` | Relative or absolute file path to the material. For cross-platform compatibility, Unix-style paths are recommended.
| 3 | string |  | Description of the material.
|===

