= General

:home-path: ../..
:imagesdir: {home-path}/_images
:includedir: {home-path}/_images

A human is a bipedal being that can be represented by an object in 3D geometry.

The human 3D geometry is generically structured into the node structure and skeleton (also often called armature) defined in xref:../07_geometry/object-human/human-index.adoc#_model_structure[Section 7.3.3.3, "Model structure"].
The structure starts with a Root node as a parent group for all other nodes in the structure.

Splitting the object into different parts, such as clothing, hair, and accessories, enables animation and exchange of parts. If a piece of equipment or accessory is specific to a human, rather small, and not self-contained or animated, it can be part of the human asset itself.
For example: Backpacks, sunglasses, and jewelry can be part of the human asset. Bicycles, scooters, and skateboards are separate objects and not part of the human asset.
Not all nodes have to be present in every human _3D model_.
Custom _object parts_ may be added to facilitate and better visualize additional use cases, but all custom parts shall adhere to the specified structure principle.

In the coordinate system for human 3D geometry, the x-axis points forwards, the y-axis points laterally, and the z-axis points upwards.
The default pose is the A-pose.
The naming convention makes it possible to mirror one side of the skeleton to the other.
The bones follow a specific bone orientation: The y-axis of a bone always follows the bone direction, regardless of whether it points laterally, upwards, or forwards. The x-axis usually faces forwards accordingly.
The name, position, and orientation of a bone are defined by the endpoint that is closer to the root in the hierarchy.
For example, the "Lower_Arm_Left" defines the point in the left elbow of the model.

The skeleton starts with a root bone positioned at the origin of the asset, the center of the bounding box projected to the ground.
This position is static and does not change relative to the asset during simulation.
When using an ASAM OpenMATERIAL 3D human asset in combination with ASAM OSI, the OSI field https://opensimulationinterface.github.io/osi-antora-generator/asamosi/latest/gen/structosi3_1_1MovingObject_1_1PedestrianAttributes.html#a75db7466abca2d283c8d64d424385c0a[bbcenter_to_root] shall be set to the vector from the center of the bounding box to the center of the ground projection of the bounding box.
This specifically means: x=0, y=0, z=-half of the bounding box height.

<<fig-human-structure>> shows the orientation of the coordinate system of a human skeleton.

[#fig-human-structure]
.Human bone structure
image::fig_human-structure.svg[,500]

Bones with a local transform are indicated in the structure by a (T).
This indicator is used in the documentation only and shall not be part of the actual node name.

An example of a human asset can be found in the examples folder of the https://github.com/asam-ev/OpenMATERIAL-3D/tree/main/examples/human_example[GitHub repository].