= Model structure

== Structure overview

[plantuml]
----
legend
|_ [[../07_geometry/object-human/human-index.html#_grp_root Grp_Root]]
  |_ [[../07_geometry/object-human/human-index.html#_armature_name Armature_<Name>]]
    |_ [[../07_geometry/object-human/human-index.html#_root Root]]
      |_ [[../07_geometry/object-human/human-index.html#_hip_t Hip]] (T)
        |_ [[../07_geometry/object-human/human-index.html#_lower_spine_t Lower_Spine]] (T)
          |_ [[../07_geometry/object-human/human-index.html#_upper_spine_t Upper_Spine]] (T)
            |_ [[../07_geometry/object-human/human-index.html#_neck_t Neck]] (T)
              |_ [[../07_geometry/object-human/human-index.html#_head_t Head]] (T)
                |_ [[../07_geometry/object-human/human-index.html#_eye_left_t Eye_Left]] (T)
                |_ [[../07_geometry/object-human/human-index.html#_eye_right_t Eye_Right]] (T)
          |_ [[../07_geometry/object-human/human-index.html#_shoulder_left_t Shoulder_Left]] (T)
            |_ [[../07_geometry/object-human/human-index.html#_upper_arm_left_t Upper_Arm_Left]] (T)
              |_ [[../07_geometry/object-human/human-index.html#_lower_arm_left_t Lower_Arm_Left]] (T)
                |_ [[../07_geometry/object-human/human-index.html#_hand_left_t Hand_Left]] (T)
                  |_ [[../07_geometry/object-human/human-index.html#_full_fingers_left_t Full_Fingers_Left]] (T)
                  |_ [[../07_geometry/object-human/human-index.html#_full_thumb_left_t Full_Thumb_Left]] (T)
          |_ [[../07_geometry/object-human/human-index.html#_shoulder_right_t Shoulder_Right]] (T)
            |_ [[../07_geometry/object-human/human-index.html#_upper_arm_right_t Upper_Arm_Right]] (T)
              |_ [[../07_geometry/object-human/human-index.html#_lower_arm_right_t Lower_Arm_Right]] (T)
                |_ [[../07_geometry/object-human/human-index.html#_hand_right_t Hand_Right]] (T)
                  |_ [[../07_geometry/object-human/human-index.html#_full_fingers_right_t Full_Fingers_Right]] (T)
                  |_ [[../07_geometry/object-human/human-index.html#_full_thumb_right_t Full_Thumb_Right]] (T)
        |_ [[../07_geometry/object-human/human-index.html#_upper_leg_left_t Upper_Leg_Left]] (T)
          |_ [[../07_geometry/object-human/human-index.html#_lower_leg_left_t Lower_Leg_Left]] (T)
            |_ [[../07_geometry/object-human/human-index.html#_foot_left_t Foot_Left]] (T)
              |_ [[../07_geometry/object-human/human-index.html#_full_toes_left_t Full_Toes_Left]] (T)
        |_ [[../07_geometry/object-human/human-index.html#_upper_leg_right_t Upper_Leg_Right]] (T)
          |_ [[../07_geometry/object-human/human-index.html#_lower_leg_right_t Lower_Leg_Right]] (T)
            |_ [[../07_geometry/object-human/human-index.html#_foot_right_t Foot_Right]] (T)
              |_ [[../07_geometry/object-human/human-index.html#_full_toes_right_t Full_Toes_Right]] (T)
    |_ [[../07_geometry/object-human/human-index.html#_accessories_name Accessories_<Name>]]
    |_ [[../07_geometry/object-human/human-index.html#_body_name Body_<Name>]]
    |_ [[../07_geometry/object-human/human-index.html#_clothing_name Clothing_<Name>]]
    |_ [[../07_geometry/object-human/human-index.html#_hair_name Hair_<Name>]]
end legend
----

== Grp_Root

This group is used as a parent for all following nodes. It can be used to place the whole asset and select the complete node hierarchy at once. The transformation is set to 0 for all axes.

[#tab-human-Grp_Root]
.Grp_Root
[%header, cols="20, 80"]
|===

2+^| Grp_Root

| *Origin*
| Center of the bounding box on the ground

| *x-axis*
| Pointing forwards

| *y-axis*
| Pointing laterally

| *z-axis*
| Pointing upwards
|===


== Armature_<Name>

This object or group represents the armature (skeleton) of the object and contains all bones. It is needed to ensure that the bone hierarchy can be exported and imported correctly.
Depending on the 3D software, the armature is a separate _object type_ (for example in Blender) or represented by a group (for example in Maya).
The suffix `_<Name>` is optional. It is recommended when multiple human assets are prepared in a single file of a 3D application, in order to keep the names unique and within the naming convention.
The armature shares the coordinate system with Grp_Root.


== Root

The Root bone is the parent bone for all other bones. It can be used to control the whole skeleton. It shares the coordinate system with Grp_Root, see <<tab-human-Grp_Root>>.

== Hip (T)

The Hip bone represents the lowest parts and bones of the spine, that is, the Hip, Coccyx, and Sacrum spine bones of the human skeleton.

[#tab-human-hip]
.Hip bone
[%header, cols="20, 80"]
|===

2+^| Hip

| *Origin*
| At the height of the Coccyx bone and in the middle of the geometry

| *x-axis*
| Pointing forwards

| *y-axis*
| Pointing along the bone direction

| *z-axis*
| Pointing laterally
|===


== Lower_Spine (T)

The Lower_Spine bone represents the middle parts and bones of the spine, that is, the Lumbar spine bones of the human skeleton.

[#tab-human-lower-spine]
.Lower_Spine bone
[%header, cols="20, 80"]
|===

2+^| Lower_Spine

| *Origin*
| At the height of the first Lumbar spine bone and in the middle of the geometry

| *x-axis*
| Pointing forwards

| *y-axis*
| Pointing along the bone direction

| *z-axis*
| Pointing laterally
|===


== Upper_Spine (T)

The Upper_Spine bone represents the upper parts and bones of the spine, that is, the Thoracic spine bones of the human skeleton.

[#tab-human-upper-spine]
.Upper_Spine bone
[%header, cols="20, 80"]
|===

2+^| Upper_Spine

| *Origin*
| At the height of the lowest Thoracic spine bone and in the middle of the geometry

| *x-axis*
| Pointing forwards

| *y-axis*
| Pointing along the bone direction

| *z-axis*
| Pointing laterally
|===


== Neck (T)

The Neck bone represents the uppermost parts and bones of the spine, that is, the Cervical spine bones of the human skeleton.

[#tab-human-neck]
.Neck bone
[%header, cols="20, 80"]
|===

2+^| Neck

| *Origin*
| At the height of the lowest Cervical spine bone and in the middle of the geometry

| *x-axis*
| Pointing forwards

| *y-axis*
| Pointing along the bone direction

| *z-axis*
| Pointing laterally
|===


== Head (T)

The Head bone represents the head, that is, the skull of the human skeleton.

[#tab-human-head]
.Head bone
[%header, cols="20, 80"]
|===

2+^| Head

| *Origin*
| At the height of the first Cervical spine bone and in the middle of the geometry

| *x-axis*
| Pointing forwards

| *y-axis*
| Pointing along the bone direction

| *z-axis*
| Pointing laterally
|===


== Eye_Left (T)

The Eye_Left bone represents the left eye of the human body. It is used to calculate the eye level.

[#tab-human-eye-left]
.Eye_Left bone
[%header, cols="20, 80"]
|===

2+^| Eye_Left

| *Origin*
| At the middle of the (eyeball) geometry

| *x-axis*
| Pointing upwards

| *y-axis*
| Pointing along the bone direction

| *z-axis*
| Pointing laterally
|===


== Eye_Right (T)

The Eye_Right bone represents the right eye of the human body. It is used to calculate the eye level.

[#tab-human-eye-right]
.Eye_Right bone
[%header, cols="20, 80"]
|===

2+^| Eye_Right

| *Origin*
| At the middle of the (eyeball) geometry

| *x-axis*
| Pointing upwards

| *y-axis*
| Pointing along the bone direction

| *z-axis*
| Pointing laterally
|===


== Shoulder_Left (T)

The Shoulder_Left bone represents the upper part of the left shoulder, that is, the interaction between the Clavicle bone and the Humerus head of the human skeleton.

[#tab-human-shoulder-left]
.Shoulder_Left bone
[%header, cols="20, 80"]
|===

2+^| Shoulder_Left

| *Origin*
| At the height of the Clavicle bone and in the middle of the geometry

| *x-axis*
| Pointing forwards

| *y-axis*
| Pointing along the bone direction

| *z-axis*
| Pointing laterally
|===


== Upper_Arm_Left (T)

The Upper_Arm_Left bone represents the upper part of the left arm, that is, the Humerus head of the human skeleton.

[#tab-human-upper-arm-left]
.Upper_Arm_Left bone
[%header, cols="20, 80"]
|===

2+^| Upper_Arm_Left

| *Origin*
| At the height of the Humerus head and in the middle of the geometry

| *x-axis*
| Pointing forwards

| *y-axis*
| Pointing along the bone direction

| *z-axis*
| Pointing laterally
|===


== Lower_Arm_Left (T)

The Lower_Arm_Left bone represents the lower part of the left arm, that is, the left elbow and Radius and Ulna of the human skeleton.

[#tab-human-lower-arm-left]
.Lower_Arm_Left bone
[%header, cols="20, 80"]
|===

2+^| Lower_Arm_Left

| *Origin*
| At the height of the elbow and in the middle of the geometry

| *x-axis*
| Pointing forwards

| *y-axis*
| Pointing along the bone direction

| *z-axis*
| Pointing laterally
|===


== Hand_Left (T)

The Hand_Left bone represents the left hand, that is, the left carpal bones of the human skeleton.
When used with ASAM OSI, this bone corresponds to TYPE_FULL_HAND_L in the PedestrianAttributes.

[#tab-human-hand-left]
.Hand_Left bone
[%header, cols="20, 80"]
|===

2+^| Hand_Left

| *Origin*
| At the height of the proximal carpal bones and in the middle of the geometry

| *x-axis*
| Pointing forwards

| *y-axis*
| Pointing along the bone direction

| *z-axis*
| Pointing laterally
|===


== Full_Thumb_Left (T)

The Full_Thumb_Left bone represents the thumb of the left hand, that is, the full thumb of the human skeleton.

[#tab-human-full-thumb-left]
.Full_Thumb_Left bone
[%header, cols="20, 80"]
|===

2+^| Full_Thumb_Left

| *Origin*
| At the height of the proximal carpal bones and in the middle of the geometry

| *x-axis*
| Pointing forwards

| *y-axis*
| Pointing along the bone direction

| *z-axis*
| Pointing laterally
|===


== Full_Fingers_Left (T)

The Full_Fingers_Left bone represents all other fingers of the left hand, that is, the full index finger, middle finger, ring finger, and little finger of the human skeleton. The middle finger position and length are used to place the bone correctly.

[#tab-human-full-fingers-left]
.Full_Fingers_Left bone
[%header, cols="20, 80"]
|===

2+^| Full_Fingers_Left

| *Origin*
| At the height of the proximal carpal bones and in the middle of the hand geometry

| *x-axis*
| Pointing forwards

| *y-axis*
| Pointing along the bone direction

| *z-axis*
| Pointing laterally
|===


== Shoulder_Right (T)

The Shoulder_Right bone represents the upper part of the right shoulder, that is, the interaction between the Clavicle bone and the Humerus head of the human skeleton.

[#tab-human-shouder-right]
.Shoulder_Right bone
[%header, cols="20, 80"]
|===

2+^| Shoulder_Right

| *Origin*
| At the height of the Clavicle bone and in the middle of the geometry

| *x-axis*
| Pointing forwards

| *y-axis*
| Pointing along the bone direction

| *z-axis*
| Pointing laterally
|===


== Upper_Arm_Right (T)

The Upper_Arm_Right bone represents the upper part of the right arm, that is, the Humerus head of the human skeleton.

[#tab-human-upper-arm-right]
.Upper_Arm_Right bone
[%header, cols="20, 80"]
|===

2+^| Upper_Arm_Right

| *Origin*
| At the height of the Humerus head and in the middle of the geometry

| *x-axis*
| Pointing forwards

| *y-axis*
| Pointing along the bone direction

| *z-axis*
| Pointing laterally
|===


== Lower_Arm_Right (T)

The Lower_Arm_Right bone represents the lower part of the right arm, that is, the right elbow and Radius and Ulna of the human skeleton.

[#tab-human-lower-arm-right]
.Lower_Arm_Right bone
[%header, cols="20, 80"]
|===

2+^| Lower_Arm_Right

| *Origin*
| At the height of the elbow and in the middle of the geometry

| *x-axis*
| Pointing forwards

| *y-axis*
| Pointing along the bone direction

| *z-axis*
| Pointing laterally
|===


== Hand_Right (T)

The Hand_Right bone represents the right hand, that is, the right carpal bones of the human skeleton.
When used with ASAM OSI, this bone corresponds to TYPE_FULL_HAND_R in the PedestrianAttributes.

[#tab-human-hand-right]
.Hand_Right bone
[%header, cols="20, 80"]
|===

2+^| Hand_Right

| *Origin*
| At the height of the proximal carpal bones and in the middle of the geometry

| *x-axis*
| Pointing forwards

| *y-axis*
| Pointing along the bone direction

| *z-axis*
| Pointing laterally
|===


== Full_Thumb_Right (T)

The Full_Thumb_Right bone represents the thumb of the right hand, that is, the full thumb of the human skeleton.

[#tab-human-full-thumb-right]
.Full_Thumb_Right bone
[%header, cols="20, 80"]
|===

2+^| Full_Thumb_Right

| *Origin*
| At the height of the proximal carpal bones and in the middle of the geometry

| *x-axis*
| Pointing forwards

| *y-axis*
| Pointing along the bone direction

| *z-axis*
| Pointing laterally
|===


== Full_Fingers_Right (T)

The Full_Fingers_Right bone represents all other fingers of the right hand, that is, the full index finger, middle finger, ring finger, and little finger of the human skeleton. The middle finger position and length are used to place the bone correctly.

[#tab-human-full-fingers-right]
.Full_Fingers_Right bone
[%header, cols="20, 80"]
|===

2+^| Full_Fingers_Right

| *Origin*
| At the height of the proximal carpal bones and in the middle of the hand geometry

| *x-axis*
| Pointing forwards

| *y-axis*
| Pointing along the bone direction

| *z-axis*
| Pointing laterally
|===

== Upper_Leg_Left (T)

The Upper_Leg_Left bone represents the upper part of the left leg, that is, the thigh of the human skeleton. It controls the hip joint.

[#tab-human-upper-leg-left]
.Upper_Leg_Left bone
[%header, cols="20, 80"]
|===

2+^| Upper_Leg_Left (T)

| *Origin*
| At the height of the hip joint and in the middle of the geometry

| *x-axis*
| Pointing forwards

| *y-axis*
| Pointing along the bone direction

| *z-axis*
| Pointing laterally
|===


== Lower_Leg_Left (T)

The Lower_Leg_Left bone represents the lower part of the left leg, that is, the Tibia and Fibula of the human skeleton. It controls the knee.

[#tab-human-lower-leg-left]
.Lower_Leg_Left bone
[%header, cols="20, 80"]
|===

2+^| Lower_Leg_Left

| *Origin*
| At the height of the knee and in the middle of the geometry

| *x-axis*
| Pointing forwards

| *y-axis*
| Pointing along the bone direction

| *z-axis*
| Pointing laterally
|===


== Foot_Left (T)

The Foot_Left bone represents the left foot of the human skeleton without the toes. It controls the ankle.
When used with ASAM OSI, this bone corresponds to TYPE_FULL_Foot_L in the PedestrianAttributes.

[#tab-human-foot-left]
.Foot_Left bone
[%header, cols="20, 80"]
|===

2+^| Foot_Left

| *Origin*
| At the height of the ankle and in the middle of the geometry

| *x-axis*
| Pointing upwards

| *y-axis*
| Pointing along the bone direction

| *z-axis*
| Pointing laterally
|===


== Full_Toes_Left (T)

The Full_Toes_Left bone represents all toes of the left foot of the human skeleton.

[#tab-human-full-toes-left]
.Full_Toes_Left bone
[%header, cols="20, 80"]
|===

2+^| Full_Toes_Left

| *Origin*
| At the height of the phalanges and in the middle of the geometry

| *x-axis*
| Pointing upwards

| *y-axis*
| Pointing along the bone direction

| *z-axis*
| Pointing laterally
|===


== Upper_Leg_Right (T)

The Upper_Leg_Right bone represents the upper part of the right leg, that is, the thigh of the human skeleton. It controls the hip joint.

[#tab-human-upper-leg-right]
.Upper_Leg_Right bone
[%header, cols="20, 80"]
|===

2+^| Upper_Leg_Right

| *Origin*
| At the height of the hip joint and in the middle of the geometry

| *x-axis*
| Pointing forwards

| *y-axis*
| Pointing along the bone direction

| *z-axis*
| Pointing laterally
|===


== Lower_Leg_Right (T)

The Lower_Leg_Right bone represents the lower part of the right leg, that is, the Tibia and Fibula of the human skeleton. It controls the knee.

[#tab-human-lower-leg-right]
.Lower_Leg_Right bone
[%header, cols="20, 80"]
|===

2+^| Lower_Leg_Right

| *Origin*
| At the height of the knee and in the middle of the geometry

| *x-axis*
| Pointing forwards

| *y-axis*
| Pointing along the bone direction

| *z-axis*
| Pointing laterally
|===


== Foot_Right (T)

The Foot_Right bone represents the right foot of the human skeleton without the toes. It controls the ankle.
When used with ASAM OSI, this bone corresponds to TYPE_FULL_Foot_R in the PedestrianAttributes.

[#tab-human-foot-right]
.Foot_Right bone
[%header, cols="20, 80"]
|===

2+^| Foot_Right

| *Origin*
| At the height of the ankle and in the middle of the geometry

| *x-axis*
| Pointing upwards

| *y-axis*
| Pointing along the bone direction

| *z-axis*
| Pointing laterally
|===


== Full_Toes_Right (T)

The Full_Toes_Right bone represents all toes of the right foot of the human skeleton.

[#tab-human-full-toes-right]
.Full_Toes_Right bone
[%header, cols="20, 80"]
|===

2+^| Full_Toes_Right

| *Origin*
| At the height of the phalanges and in the middle of the geometry

| *x-axis*
| Pointing upwards

| *y-axis*
| Pointing along the bone direction

| *z-axis*
| Pointing laterally
|===

== Accessories_<Name>

This object represents an additional or exchangeable accessory of the human. It shares the coordinate system with Grp_Root, see <<tab-human-Grp_Root>>.

== Body_<Name>

This object represents the body of the human. It shares the coordinate system with Grp_Root, see <<tab-human-Grp_Root>>.

== Clothing_<Name>

This object represents an additional or exchangeable clothing part of the human. It shares the coordinate system with Grp_Root, see <<tab-human-Grp_Root>>.

== Hair_<Name>

This object represents an additional or exchangeable hair part of the human. It shares the coordinate system with Grp_Root, see <<tab-human-Grp_Root>>.