= Material brdf schema

== metadata

The key meta information about the BRDF look-up table.


*Type:* `+object+` +
*Required:* Yes

=== name
The display name of the material, such as 'Red brick' or 'Dark asphalt'.

*Type:* `+string+` +
*Required:* Yes


=== description
Short description of the material in 2 - 3 sentences.

*Type:* `+string+` +
*Required:* No


=== uuid
Universally unique identifier for the material in 8-4-4-4-12 format, see cite:[uui]. The uuid stays the same, even if version is updated.

*Type:* `+string+` +
*Pattern:* `+\\b[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}\\b$+` +
*Required:* Yes


=== materialVersion
The version number of the material, following semantic versioning (for example, '1.0.0').

*Type:* `+string+` +
*Pattern:* `+^\\d+\\.\\d+\\.\\d+$+` +
*Required:* Yes


=== openMaterial3dVersion
The version of the ASAM OpenMATERIAL 3D specification used, adhering to semantic versioning (for example, '1.0.0').

*Type:* `+string+` +
*Pattern:* `+^\\d+\\.\\d+\\.\\d+$+` +
*Required:* Yes


=== copyrights
Indicates copyright details, including the year and copyright holder (for example, '© 2024 ACME Inc.').

*Type:* `+array+` +
*Required:* Yes




=== license
Describes the license for material distribution. Use an SPDX identifier for open-source licenses (for example, 'MIT'), or provide a URL or filename for proprietary licenses.

*Type:* `+string+` +
*Required:* Yes


=== authors
Lists the author(s) of the material as a name, email, or company.

*Type:* `+array+` +
*Required:* Yes




=== creationDate
The date and time of material creation, formatted as YYYYMMDDTHHMMSSZ according to ISO 8601 cite:[iso8601] (for example, '20240703T101728Z').

*Type:* `+string+` +
*Pattern:* `+^\\d{8}T\\d{6}Z$+` +
*Required:* No


=== sources
Source of the BRDF data. Was it measured, simulated, or taken from literature? Multiple sources should be comma-separated.

*Type:* `+string+` +
*Required:* Yes


=== typicalSensorTechnology
Typical sensor technology this BRDF table is used for. Examples: 'radar', 'lidar', 'camera'. If more than one applies, use comma-separation.

*Type:* `+string+` +
*Required:* No


== brdf

The BRDF is used as a basic quantity to characterize the reflecting properties of a surface geometrically. The following BRDF definition applies: “The ratio of the radiance or power per unit solid-angle in the outgoing direction from a unit projected surface area to the collimated irradiance or power per unit projected surface area.” A physically plausible BRDF shall additionally obey the following three properties. (1) Positivity: The BRDF has units of inverse steradians (1/sr) and can vary from 0 to infinity. (2) Helmholtz reciprocity: It is symmetric in the incoming and outgoing direction. (3) Energy conservation: No more radiant energy is reflected from a point on the surface than incident radiant energy to that point. 


*Type:* `+object+` +
*Required:* Yes

=== wavelengths
List of all wavelengths in meters contained in the lookup table. The wavelength values shall be within the range of 1e-09 to 17.16e-03 (upper limit corresponds to 20 kHz).

*Type:* `+array+` +
*Required:* Yes




=== receiverSolidAngles
List of all receiver solid angles in steradians (sr) used to measure the BRDF data. The solid angles are given as a key-value pair mapped to the wavelengths contained in the lookup table. In case of primary receiver optics in front of the detector, an assumed solid angle defined by the optics aperture shall be given here. The necessity of this field is based on common laser measurement standards, such as SEMI ME1392-0116 (2023) and EN ISO 19986:2020.

*Type:* `+array+` +
*Required:* No

==== wavelength
Wavelength of radiation in free-space in meters (m). The value shall be within the range of 1e-09 to 17.16e-03 (upper limit corresponds to 20 kHz).

*Type:* `+number+` +
*Minimum value:* `+1e-09+` +
*Maximum value:* `+0.01716+` +
*Required:* Yes


==== solidAngle
Receiver solid angle in steradians (sr). The value shall be greater than 0.

*Type:* `+number+` +
*Required:* Yes



=== lookupTable
Array of bidirectional reflectance distribution function (BRDF) values. The array shall be sorted based on the columns starting with the first.

*Type:* `+array+` +
*Required:* Yes


Columns of the table:

- Column 1: Wavelength of radiation in free-space in meters (m). The value shall be within the range of 1e-09 to 17.16e-03 (upper limit corresponds to 20 kHz).
- Column 2: Incident zenith angle relative to the surface normal in rad. It shall be within a range of \(0\) to \(\pi/2\).
- Column 3: Exit zenith angle relative to the surface normal in rad. It shall be within a range of \(0\) to \(\pi/2\).
- Column 4: Exit azimuth angle in rad. It shall be within a range of \(0\) to \(2 \pi\). The value is relative to the incident azimuth angle. The incident azimuth angle is set to 0° as the incident ray is used as reference.
- Column 5: BRDF value in 1/sr. The minimum values is 0.


