= Material emp schema

== Overview

This is the documentation about the JSON schema file. The actual file is located in the ASAM OpenMATERIAL 3D link:https://github.com/asam-ev/OpenMATERIAL-3D/blob/main/schemas/material_emp_schema.json[GitHub repository].

The following diagram shows the hierarchy of the fields defined in this schema. Fields marked with `\(R)` are required. A field can be optional while some of its children are required. In that case, the required children only have to be filled in if the optional parent field is present.

[plantuml]
----
legend
Material emp schema
|_ [[../08_material/material-emp-schema.html#_metadata metadata]] (R)
  |_ [[../08_material/material-emp-schema.html#_name name]] (R)
  |_ [[../08_material/material-emp-schema.html#_description description]]
  |_ [[../08_material/material-emp-schema.html#_uuid uuid]] (R)
  |_ [[../08_material/material-emp-schema.html#_materialversion materialVersion]] (R)
  |_ [[../08_material/material-emp-schema.html#_openmaterial3dversion openMaterial3dVersion]] (R)
  |_ [[../08_material/material-emp-schema.html#_copyrights copyrights]] (R)
  |_ [[../08_material/material-emp-schema.html#_license license]] (R)
  |_ [[../08_material/material-emp-schema.html#_authors authors]] (R)
  |_ [[../08_material/material-emp-schema.html#_creationdate creationDate]]
  |_ [[../08_material/material-emp-schema.html#_sources sources]] (R)
|_ [[../08_material/material-emp-schema.html#_electromagneticproperties electromagneticProperties]] (R)
end legend
----

== metadata

The key meta information about the EMP look-up table.


*Type:* `++object++` +
*Required:* Yes

=== name
The display name of the material, such as 'Red brick' or 'Dark asphalt'.

*Type:* `++string++` +
*Required:* Yes


=== description
Short description of the material in two to three sentences.

*Type:* `++string++` +
*Required:* No


=== uuid
Universally unique identifier for the material in 8-4-4-4-12 format, see cite:[uui]. The uuid stays the same, even if version is updated.

*Type:* `++string++` +
*Pattern:* `++\b[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}\b$++` +
*Required:* Yes


=== materialVersion
The version number of the material, following semantic versioning (for example, '1.0.0').

*Type:* `++string++` +
*Pattern:* `++^\d+\.\d+\.\d+$++` +
*Required:* Yes


=== openMaterial3dVersion
The version of the ASAM OpenMATERIAL 3D specification used, adhering to semantic versioning (for example, '1.0.0').

*Type:* `++string++` +
*Pattern:* `++^\d+\.\d+\.\d+$++` +
*Required:* Yes


=== copyrights
Indicates copyright details, including the year and copyright holder (for example, '© 2024 ACME Inc.').

*Type:* `++array++` +
*Item count:* `++at least 1++` +
*Item type:* `++string++` +
*Required:* Yes


=== license
Describes the license for material distribution. Use an SPDX identifier for open-source licenses (for example, 'MIT'), or provide a URL or filename for proprietary licenses.

*Type:* `++string++` +
*Required:* Yes


=== authors
Lists the author(s) of the material as a name, email, or company.

*Type:* `++array++` +
*Item count:* `++at least 1++` +
*Item type:* `++string++` +
*Required:* Yes


=== creationDate
The date and time of material creation, formatted as YYYYMMDDTHHMMSSZ according to ISO 8601 cite:[iso8601] (for example, '20240703T101728Z').

*Type:* `++string++` +
*Pattern:* `++^\d{8}T\d{6}Z$++` +
*Required:* No


=== sources
Sources of the electromagnetic property data. Was it measured, simulated, or taken from literature? Multiple sources should be comma-separated.

*Type:* `++string++` +
*Required:* Yes


== electromagneticProperties

Array of electromagnetic property values, with each item representing a different property. The array shall be sorted based on the columns starting with the first.


*Type:* `++array++` +
*Required:* Yes


*Column count:* `++exactly 7++`

Columns of the table:

[cols="1,2,2,6",options="header"]
|===
| Column | Type | Constraints | Description

| 1 | number or null | `++[1e-09, 0.01716]++` | Wavelength of the radiation in free space. Unit: meter (m). The upper limit corresponds to 20 kHz.
| 2 | number or null | `++[0, inf[++` | Temperature of the material. Unit: kelvin (K).
| 3 | number or null | `++[0, 100]++` | Relative humidity of the material. Unit: percent (%).
| 4 | number or null | `++[1, inf[++` | Real part of complex relative permeability of the material, which is \(\mu_{\textrm{r}}^{'}\) in \(\mu_r = \mu_{\textrm{r}}^{'} - j \mu_{\textrm{r}}^{''}\).
| 5 | number or null | `++[0, inf[++` | Imaginary part of complex relative permeability of the material, which is \(\mu_{\textrm{r}}^{''}\) in \(\mu_{\textrm{r}} = \mu_{\textrm{r}}^{'} - j \mu_{\textrm{r}}^{''}\).
| 6 | number or null |  | Real part of complex relative permittivity of the material, which is \(\epsilon_{\textrm{r}}^{'}\) in \(\epsilon_{\textrm{r}} = \epsilon_{\textrm{r}}^{'} - j \epsilon_{\textrm{r}}^{''}\).
| 7 | number or null | `++[0, inf[++` | Imaginary part of complex relative permittivity of the material, which is \(\epsilon_{\textrm{r}}^{''}\) in \(\epsilon_{\textrm{r}} = \epsilon_{\textrm{r}}^{'} - j \epsilon_{\textrm{r}}^{''}\).
|===

