= Material optical schema

== Overview

This is the documentation about the JSON schema file. The actual file is located in the ASAM OpenMATERIAL 3D link:https://github.com/asam-ev/OpenMATERIAL-3D/blob/main/schemas/material_optical_schema.json[GitHub repository].

The following diagram shows the hierarchy of the fields defined in this schema. Fields marked with `\(R)` are required. A field can be optional while some of its children are required. In that case, the required children only have to be filled in if the optional parent field is present.

[plantuml]
----
legend
Material optical schema
|_ [[../08_material/material-optical-schema.html#_metadata metadata]] (R)
  |_ [[../08_material/material-optical-schema.html#_name name]] (R)
  |_ [[../08_material/material-optical-schema.html#_description description]]
  |_ [[../08_material/material-optical-schema.html#_uuid uuid]] (R)
  |_ [[../08_material/material-optical-schema.html#_materialversion materialVersion]] (R)
  |_ [[../08_material/material-optical-schema.html#_openmaterial3dversion openMaterial3dVersion]] (R)
  |_ [[../08_material/material-optical-schema.html#_copyrights copyrights]] (R)
  |_ [[../08_material/material-optical-schema.html#_license license]] (R)
  |_ [[../08_material/material-optical-schema.html#_authors authors]] (R)
  |_ [[../08_material/material-optical-schema.html#_creationdate creationDate]]
  |_ [[../08_material/material-optical-schema.html#_sources sources]] (R)
|_ [[../08_material/material-optical-schema.html#_opticalproperties opticalProperties]] (R)
end legend
----

== metadata

The key meta information about the optical look-up table.


*Type:* `++object++` +
*Required:* Yes

=== name
The display name of the material, such as 'Red brick' or 'Dark asphalt'.

*Type:* `++string++` +
*Required:* Yes


=== description
Short description of the material in 2 - 3 sentences.

*Type:* `++string++` +
*Required:* No


=== uuid
Universally unique identifier for the material in 8-4-4-4-12 format, see cite:[uui]. The uuid stays the same, even if version is updated.

*Type:* `++string++` +
*Pattern:* `++\b[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}\b$++` +
*Required:* Yes


=== materialVersion
The version number of the material, following semantic versioning (for example, '1.0.0').

*Type:* `++string++` +
*Pattern:* `++^\d+\.\d+\.\d+$++` +
*Required:* Yes


=== openMaterial3dVersion
The version of the ASAM OpenMATERIAL 3D specification used, adhering to semantic versioning (for example, '1.0.0').

*Type:* `++string++` +
*Pattern:* `++^\d+\.\d+\.\d+$++` +
*Required:* Yes


=== copyrights
Indicates copyright details, including the year and copyright holder (e.g., '© 2024 ACME Inc.').

*Type:* `++array++` +
*Item count:* `++at least 1++` +
*Item type:* `++string++` +
*Required:* Yes


=== license
Describes the license for material distribution. Use an SPDX identifier for open-source licenses (for example, 'MIT'), or provide a URL or filename for proprietary licenses.

*Type:* `++string++` +
*Required:* Yes


=== authors
Lists the author(s) of the material as a name, email, or company.

*Type:* `++array++` +
*Item count:* `++at least 1++` +
*Item type:* `++string++` +
*Required:* Yes


=== creationDate
The date and time of material creation, formatted as YYYYMMDDTHHMMSSZ according to ISO 8601 cite:[iso8601] (for example, '20240703T101728Z').

*Type:* `++string++` +
*Pattern:* `++^\d{8}T\d{6}Z$++` +
*Required:* No


=== sources
Sources of the optical property data. Was it measured, simulated, or taken from literature? Multiple sources should be comma-separated.

*Type:* `++string++` +
*Required:* Yes


== opticalProperties




*Type:* `++array++` +
*Required:* Yes

Array of optical property values, with each item representing a different property. The array shall be sorted based on the columns starting with the first.

*Column count:* `++exactly 4++`

Columns of the table:

[cols="1,2,2,6",options="header"]
|===
| Column | Type | Constraints | Description

| 1 | number or null | `++[1e-09, 0.01716]++` | Wavelength of radiation in free-space in meters (m). The upper limit corresponds to 20 kHz.
| 2 | number or null | `++[0, inf[++` | Temperature of material in Kelvin (K).
| 3 | number or null | `++[0, inf[++` | Real part of index of refraction of material, which is \(n^{'}\) in \(n = n^{'} - j \kappa\).
| 4 | number or null | `++[0, inf[++` | Imaginary part of index of refraction of material, which is \(\kappa\) in \(n = n^{'} - j \kappa\).
|===

