= Material schema

== Overview

This is the documentation about the JSON schema file. The actual file is located in the ASAM OpenMATERIAL 3D link:https://github.com/asam-ev/OpenMATERIAL-3D/blob/main/schemas/material_schema.json[GitHub repository].

The following diagram shows the hierarchy of the fields defined in this schema. Fields marked with `\(R)` are required. A field can be optional while some of its children are required. In that case, the required children only have to be filled in if the optional parent field is present.

[plantuml]
----
legend
Material schema
|_ [[../08_material/material-schema.html#_metadata metadata]] (R)
  |_ [[../08_material/material-schema.html#_name name]] (R)
  |_ [[../08_material/material-schema.html#_description description]]
  |_ [[../08_material/material-schema.html#_uuid uuid]] (R)
  |_ [[../08_material/material-schema.html#_materialversion materialVersion]] (R)
  |_ [[../08_material/material-schema.html#_openmaterial3dversion openMaterial3dVersion]] (R)
  |_ [[../08_material/material-schema.html#_copyrights copyrights]] (R)
  |_ [[../08_material/material-schema.html#_license license]] (R)
  |_ [[../08_material/material-schema.html#_authors authors]] (R)
  |_ [[../08_material/material-schema.html#_creationdate creationDate]]
|_ [[../08_material/material-schema.html#_materialproperties materialProperties]] (R)
  |_ [[../08_material/material-schema.html#_surfaceroughness surfaceRoughness]]
    |_ [[../08_material/material-schema.html#_surfaceheightrms surfaceHeightRms]] (R)
    |_ [[../08_material/material-schema.html#_surfacecorrelationlength surfaceCorrelationLength]] (R)
    |_ [[../08_material/material-schema.html#_sources sources]] (R)
  |_ [[../08_material/material-schema.html#_emissivitydata emissivityData]]
    |_ [[../08_material/material-schema.html#_emissivitycoefficient emissivityCoefficient]] (R)
    |_ [[../08_material/material-schema.html#_temperature temperature]] (R)
    |_ [[../08_material/material-schema.html#_sources_2 sources]] (R)
  |_ [[../08_material/material-schema.html#_elasticitydata elasticityData]]
    |_ [[../08_material/material-schema.html#_youngsmodulus youngsModulus]] (R)
    |_ [[../08_material/material-schema.html#_poissonsratio poissonsRatio]] (R)
    |_ [[../08_material/material-schema.html#_sources_3 sources]] (R)
  |_ [[../08_material/material-schema.html#_densitydata densityData]]
    |_ [[../08_material/material-schema.html#_density density]] (R)
    |_ [[../08_material/material-schema.html#_sources_4 sources]] (R)
  |_ [[../08_material/material-schema.html#_retroreflectivitydata retroreflectivityData]]
    |_ [[../08_material/material-schema.html#_coefficientofretroreflection coefficientOfRetroreflection]] (R)
    |_ [[../08_material/material-schema.html#_sources_5 sources]] (R)
  |_ [[../08_material/material-schema.html#_electromagneticpropertiesuri electromagneticPropertiesUri]]
  |_ [[../08_material/material-schema.html#_opticalpropertiesuri opticalPropertiesUri]]
  |_ [[../08_material/material-schema.html#_brdfuris brdfUris]]
  |_ [[../08_material/material-schema.html#_reflectioncoefficienturis reflectionCoefficientUris]]
  |_ [[../08_material/material-schema.html#_customproperties customProperties]]
end legend
----

== metadata

The key meta information about the material properties.


*Type:* `++object++` +
*Required:* Yes

=== name
The display name of the material, such as 'Red brick' or 'Dark asphalt'.

*Type:* `++string++` +
*Required:* Yes


=== description
Short description of the material in two to three sentences.

*Type:* `++string++` +
*Required:* No


=== uuid
Universally unique identifier for the material in 8-4-4-4-12 format, see cite:[uui]. The uuid stays the same, even if version is updated.

*Type:* `++string++` +
*Pattern:* `++\b[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}\b$++` +
*Required:* Yes


=== materialVersion
The version number of the material, following semantic versioning (for example, '1.0.0').

*Type:* `++string++` +
*Pattern:* `++^\d+\.\d+\.\d+$++` +
*Required:* Yes


=== openMaterial3dVersion
The version of the ASAM OpenMATERIAL 3D specification used, adhering to semantic versioning (for example, '1.0.0').

*Type:* `++string++` +
*Pattern:* `++^\d+\.\d+\.\d+$++` +
*Required:* Yes


=== copyrights
Indicates copyright details, including the year and copyright holder (for example, '© 2024 ACME Inc.').

*Type:* `++array++` +
*Item count:* `++at least 1++` +
*Item type:* `++string++` +
*Required:* Yes


=== license
Describes the license for material distribution. Use an SPDX identifier for open-source licenses (for example, 'MIT'), or provide a URL or filename for proprietary licenses.

*Type:* `++string++` +
*Required:* Yes


=== authors
Lists the author(s) of the material as a name, email, or company.

*Type:* `++array++` +
*Item count:* `++at least 1++` +
*Item type:* `++string++` +
*Required:* Yes


=== creationDate
The date and time of material creation, formatted as YYYYMMDDTHHMMSSZ according to ISO 8601 cite:[iso8601] (for example, '20240703T101728Z').

*Type:* `++string++` +
*Pattern:* `++^\d{8}T\d{6}Z$++` +
*Required:* No


== materialProperties

Properties related to the material.


*Type:* `++object++` +
*Required:* Yes

=== surfaceRoughness
Information about the surface roughness of the material.

*Type:* `++object++` +
*Required:* No


==== surfaceHeightRms
Root mean square of the surface height deviations, also called RMS roughness. This is a vertical measure of roughness. Unit: meter (m).

*Type:* `++number++` +
*Range:* `++[0, inf[++` +
*Required:* Yes


==== surfaceCorrelationLength
Correlation length of the surface height deviations, that is, the distance after which the autocorrelation function has dropped to 1/e. This is a horizontal measure of roughness. Unit: meter (m).

*Type:* `++number++` +
*Range:* `++[0, inf[++` +
*Required:* Yes


==== sources
Sources of the surface roughness data. Multiple sources should be comma-separated.

*Type:* `++string++` +
*Required:* Yes


=== emissivityData
Emissivity data of the material.

*Type:* `++object++` +
*Required:* No


==== emissivityCoefficient
Emissivity describes the ability to emit energy as thermal radiation. It is given as the fraction of thermal radiation emitted by a surface relative to the radiation emitted by an ideal black body at the same temperature. The hemispherical total emissivity is used here, which considers the full emission over all wavelengths, directions, and polarizations at one particular temperature: ε(T).

*Type:* `++number++` +
*Range:* `++[0, 1]++` +
*Required:* Yes


==== temperature
Temperature at which the emissivity is measured. Unit: kelvin (K).

*Type:* `++number++` +
*Range:* `++[0, inf[++` +
*Required:* Yes


==== sources
Sources of the emissivity data. Multiple sources should be comma-separated.

*Type:* `++string++` +
*Required:* Yes


=== elasticityData
Information about the elasticity of the material.

*Type:* `++object++` +
*Required:* No


==== youngsModulus
Young's modulus of the material. Unit: pascal (Pa). The upper limit corresponds to the Young’s modulus of a diamond.

*Type:* `++number++` +
*Range:* `++[0, 1500000000000]++` +
*Required:* Yes


==== poissonsRatio
Poisson's ratio of the material.

*Type:* `++number++` +
*Range:* `++[-1, 0.5]++` +
*Required:* Yes


==== sources
Sources of the elasticity data. Multiple sources should be comma-separated.

*Type:* `++string++` +
*Required:* Yes


=== densityData
Information about the density of the material.

*Type:* `++object++` +
*Required:* No


==== density
Density of the material. Unit: kg/m^3^. The upper limit corresponds to the density of Osmium.

*Type:* `++number++` +
*Range:* `++[0, 25000]++` +
*Required:* Yes


==== sources
Sources of the density data. Multiple sources should be comma-separated.

*Type:* `++string++` +
*Required:* Yes


=== retroreflectivityData
Information about the retroreflective properties of the material in the visible light spectrum.

*Type:* `++object++` +
*Required:* No


==== coefficientOfRetroreflection
Coefficient of retroreflection. Unit: candela per lux per square meter (cd lx^-1^ m^-2^).

*Type:* `++number++` +
*Range:* `++[0, 5000]++` +
*Required:* Yes


==== sources
Sources of the retroreflectivity data. Multiple sources should be comma-separated.

*Type:* `++string++` +
*Required:* Yes


=== electromagneticPropertiesUri
Relative or absolute file path to a property look-up table file with electromagnetic material properties. For cross-platform compatibility, Unix-style paths are recommended.

*Type:* `++string++` +
*Pattern:* `++.*_emp\.xompt$++` +
*Required:* No


=== opticalPropertiesUri
Relative or absolute file path to a property look-up table file with optical material properties. For cross-platform compatibility, Unix-style paths are recommended.

*Type:* `++string++` +
*Pattern:* `++.*_optical\.xompt$++` +
*Required:* No


=== brdfUris
Relative or absolute file paths to one or multiple property look-up table files with wavelength-dependent bidirectional reflectance distribution functions. For cross-platform compatibility, Unix-style paths are recommended.

*Type:* `++array++` +
*Item type:* `++string++` +
*Item pattern:* `++.*_brdf\.xompt$++` +
*Required:* No


=== reflectionCoefficientUris
Relative or absolute file paths to one or multiple property look-up table files with wavelength-dependent reflection coefficient values. For cross-platform compatibility, Unix-style paths are recommended.

*Type:* `++array++` +
*Item type:* `++string++` +
*Item pattern:* `++.*_reflCoeff\.xompt$++` +
*Required:* No


=== customProperties
Non-standardized material properties for custom tools or tool chains.

*Type:* `++object++` +
*Required:* No


