= Material reflection coefficient schema

== Overview

This is the documentation about the JSON schema file. The actual file is located in the ASAM OpenMATERIAL 3D link:https://github.com/asam-ev/OpenMATERIAL-3D/blob/main/schemas/material_reflCoeff_schema.json[GitHub repository].

The following diagram shows the hierarchy of the fields defined in this schema. Fields marked with `\(R)` are required. A field can be optional while some of its children are required. In that case, the required children only have to be filled in if the optional parent field is present.

[plantuml]
----
legend
Material reflection coefficient schema
|_ [[../08_material/material-reflection-coefficient-schema.html#_metadata metadata]] (R)
  |_ [[../08_material/material-reflection-coefficient-schema.html#_name name]] (R)
  |_ [[../08_material/material-reflection-coefficient-schema.html#_description description]] (R)
  |_ [[../08_material/material-reflection-coefficient-schema.html#_uuid uuid]] (R)
  |_ [[../08_material/material-reflection-coefficient-schema.html#_materialversion materialVersion]] (R)
  |_ [[../08_material/material-reflection-coefficient-schema.html#_openmaterial3dversion openMaterial3dVersion]] (R)
  |_ [[../08_material/material-reflection-coefficient-schema.html#_copyrights copyrights]] (R)
  |_ [[../08_material/material-reflection-coefficient-schema.html#_license license]] (R)
  |_ [[../08_material/material-reflection-coefficient-schema.html#_authors authors]] (R)
  |_ [[../08_material/material-reflection-coefficient-schema.html#_creationdate creationDate]] (R)
  |_ [[../08_material/material-reflection-coefficient-schema.html#_sources sources]] (R)
|_ [[../08_material/material-reflection-coefficient-schema.html#_reflectioncoefficient reflectionCoefficient]] (R)
  |_ [[../08_material/material-reflection-coefficient-schema.html#_wavelengths wavelengths]] (R)
  |_ [[../08_material/material-reflection-coefficient-schema.html#_lookuptable lookupTable]] (R)
end legend
----

== metadata

Metadata about the material.


*Type:* `++object++` +
*Required:* Yes

=== name
The display name of the material, such as 'Red brick' or 'Dark asphalt'.

*Type:* `++string++` +
*Required:* Yes


=== description
Short description of the material in 2 - 3 sentences.

*Type:* `++string++` +
*Required:* Yes


=== uuid
Universally unique identifier for the material in 8-4-4-4-12 format, see cite:[uui]. The uuid stays the same, even if version is updated.

*Type:* `++string++` +
*Pattern:* `++\b[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}\b$++` +
*Required:* Yes


=== materialVersion
The version number of the material, following semantic versioning (for example, '1.0.0').

*Type:* `++string++` +
*Pattern:* `++^\d+\.\d+\.\d+$++` +
*Required:* Yes


=== openMaterial3dVersion
The version of the ASAM OpenMATERIAL 3D specification used, adhering to semantic versioning (for example, '1.0.0').

*Type:* `++string++` +
*Pattern:* `++^\d+\.\d+\.\d+$++` +
*Required:* Yes


=== copyrights
Indicates copyright details, including the year and copyright holder (e.g., '© 2024 ACME Inc.').

*Type:* `++array++` +
*Item count:* `++at least 1++` +
*Item type:* `++string++` +
*Required:* Yes


=== license
Describes the license for material distribution. Use an SPDX identifier for open-source licenses (for example, 'MIT'), or provide a URL or filename for proprietary licenses.

*Type:* `++string++` +
*Required:* Yes


=== authors
Lists the author(s) of the material as a name, email, or company.

*Type:* `++array++` +
*Item count:* `++at least 1++` +
*Item type:* `++string++` +
*Required:* Yes


=== creationDate
The date and time of material creation, formatted as YYYYMMDDTHHMMSSZ according to ISO 8601 cite:[iso8601] (for example, '20240703T101728Z').

*Type:* `++string++` +
*Pattern:* `++^\d{8}T\d{6}Z$++` +
*Required:* Yes


=== sources
Sources of the reflection coefficient data. Was it measured, simulated, or taken from literature? Multiple sources should be comma-separated.

*Type:* `++string++` +
*Required:* Yes


== reflectionCoefficient

Reflection coefficient lookup table including relevant meta data. The reflection coefficient is defined as the ratio of amplitudes of the reflected electromagnetic wave over the incident electromagnetic wave \(r = E_{\textrm{r}} / E_{\textrm{i}}\). This complex value is represented by angle- and wavelength-dependent magnitude and phase values.


*Type:* `++object++` +
*Required:* Yes

=== wavelengths
List of all wavelengths in meters contained in the lookup table. The upper limit corresponds to 20 kHz.

*Type:* `++array++` +
*Item type:* `++number++` +
*Item range:* `++[1e-09, 0.01716]++` +
*Required:* Yes


=== lookupTable
Array of reflection coefficient values, with each item representing a different property. The array shall be sorted based on the columns starting with the first.

*Type:* `++array++` +
*Required:* Yes


*Column count:* `++exactly 7++`

Columns of the table:

[cols="1,2,2,6",options="header"]
|===
| Column | Type | Constraints | Description

| 1 | number or null | `++[1e-09, 0.01716]++` | Wavelength of radiation in free-space in meters (m). The upper limit corresponds to 20 kHz.
| 2 | number or null | `++[0, 1.570796]++` | Incident zenith angle relative to the surface normal in rad.
| 3 | number or null | `++[0, 1.570796]++` | Exit zenith angle relative to the surface normal in rad.
| 4 | number or null | `++[0, 6.283185]++` | Exit azimuth angle in rad. The value is relative to the incident azimuth angle. The incident azimuth angle is set to 0° as the incident ray is used as reference.
| 5 | number or null | `++[0, 3.141593]++` | Polarized plane angle in rad. This is the angle between the plane containing the incident, exit, and normal vector, and the plane of polarization. The plane of polarization contains the direction of propagation and the electric vector.
| 6 | number or null | `++[0, 1]++` | Magnitude within the linearly polarized plane. The magnitude is given as an absolute relative value compared to an ideal reflector.
| 7 | number or null | `++[-3.141592, 3.141592]++` | Phase within the linearly polarized plane. If the phase is not taken into account, it is null.
|===


